### ISSUE TITLE
关于训练参数

### ISSUE THREAD

**Issue by LinyeLi60** [huanyuhello/CoDiNet#1]
作者您好，我有三个问题希望您可以解答一下

1. 关于是否跳过当前block
在训练代码中我看到不管gate的输出是什么，当前的block的运算都不会跳过，那这样如何达到加速推理的目的呢？
2.关于ConDivLoss
您没有提供lda_intra_margin和lda_inter_margin这两个值，并且loss_lda的值为0，如果直接按照您的训练命令进行训练，Consistency and Diversity Regularization loss并没有参与训练，这样就和训练普通的resnet没有什么区别
3.关于FLOPSL1Loss
我想这个loss应该是用于Customizable Dynamic Routing的，但是没看懂这个写法，您可以指点一下吗

**Comment by huanyuhello** [comment]
您好，
1. 在训练的过程中，是对所有block 进行执行，同时训练一个权值 （gumbel-softmax），即当前block 是否执行的权重。在inference 的阶段，我们对针对输出的 权重，对 block是否执行进行选择达到加速的目的。 也就是说，我们只考虑在inference阶段的加速作用。
2. 关于 condivloss的 margin， 我们建议 intra =  0.2， inter=0.5。
3. FLOPSL1Loss 是针对 总体 执行 block 的期望数量进行约束。 使网络真实执行的block的数量与我们的期望相同。 当然，这种计算量的控制方式有很多种，稍后，我会更新更多计算量的约束方式。

根据您的问题，我认为您主要没有了解 动态 网络的 选择机制： train：执行 或不执行 同时进行，并对两者进行加权。 test：根据sample adaptive 的权值，进行二值化。

**Comment by huanyuhello** [comment]
您好，我在github 上回复您的问题了，关于 Customizable Dynamic Routing 的部分，我会更新更多的实现方式。




                                                                                                                        祝好




-----原始邮件-----
发件人:lly ***@***.***>
发送时间:2021-08-04 19:40:03 (星期三)
收件人: huanyuhello/CoDiNet ***@***.***>
抄送: Subscribed ***@***.***>
主题: [huanyuhello/CoDiNet] 关于训练参数 (#1)






作者您好，我有三个问题希望您可以解答一下

关于是否跳过当前block
在训练代码中我看到不管gate的输出是什么，当前的block的运算都不会跳过，这样如果达到加速推理的目的呢？
2.关于ConDivLoss
您没有提供lda_intra_margin和lda_inter_margin这两个值，并且loss_lda的值为0，如果直接按照您的训练usage进行训练，Consistency and Diversity Regularization loss并没有参与训练
3.关于FLOPSL1Loss
我想这个loss应该是用于Customizable Dynamic Routing的，但是没看懂这个写法，您可以指点一下吗

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LinyeLi60** [comment]
感谢解答，我看明白了，您提供的代码暂时不支持推理加速，只是训练出了一个能够判断当前block是否跳过的Router，能否这么理解？
Customizable Dynamic Routing部分的代码实现和论文中的有一些差异，但是通过您的解答我看明白了，感谢！

**Comment by LinyeLi60** [comment]
能否加个微信交流一下





------------------ 原始邮件 ------------------
发件人: huanyuhello ***@***.***&gt;
发送时间: 2021年8月4日 20:27
收件人: huanyuhello/CoDiNet ***@***.***&gt;
抄送: 实名冲浪lly ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[huanyuhello/CoDiNet] 关于训练参数 (#1)





 您好，我在github 上回复您的问题了，关于 Customizable Dynamic Routing 的部分，我会更新更多的实现方式。
 
 
 
 
                                                                                                                         祝好
 
 
 
 
 -----原始邮件-----
 发件人:lly ***@***.***&gt;
 发送时间:2021-08-04 19:40:03 (星期三)
 收件人: huanyuhello/CoDiNet ***@***.***&gt;
 抄送: Subscribed ***@***.***&gt;
 主题: [huanyuhello/CoDiNet] 关于训练参数 (#1)
 
 
 
 
 
 
 作者您好，我有三个问题希望您可以解答一下
 
 关于是否跳过当前block
 在训练代码中我看到不管gate的输出是什么，当前的block的运算都不会跳过，这样如果达到加速推理的目的呢？
 2.关于ConDivLoss
 您没有提供lda_intra_margin和lda_inter_margin这两个值，并且loss_lda的值为0，如果直接按照您的训练usage进行训练，Consistency and Diversity Regularization loss并没有参与训练
 3.关于FLOPSL1Loss
 我想这个loss应该是用于Customizable Dynamic Routing的，但是没看懂这个写法，您可以指点一下吗
 
 —
 You are receiving this because you are subscribed to this thread.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huanyuhello** [comment]
要不，你在邮件中发我。。。这里好像不太方便。。。

**Comment by huanyuhello** [comment]
嗯嗯，您加我吧。 Ruming121676151




-----原始邮件-----
发件人:"实名冲浪lly" ***@***.***>
发送时间:2021-08-04 21:46:43 (星期三)
收件人: huanyuhello/CoDiNet ***@***.***>
抄送: huanyuhello ***@***.***>, "State change" ***@***.***>
主题: Re: [huanyuhello/CoDiNet] 关于训练参数 (#1)






能否加个微信交流一下





------------------ 原始邮件 ------------------
发件人: huanyuhello ***@***.***&gt;
发送时间: 2021年8月4日 20:27
收件人: huanyuhello/CoDiNet ***@***.***&gt;
抄送: 实名冲浪lly ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[huanyuhello/CoDiNet] 关于训练参数 (#1)





您好，我在github 上回复您的问题了，关于 Customizable Dynamic Routing 的部分，我会更新更多的实现方式。




祝好




-----原始邮件-----
发件人:lly ***@***.***&gt;
发送时间:2021-08-04 19:40:03 (星期三)
收件人: huanyuhello/CoDiNet ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: [huanyuhello/CoDiNet] 关于训练参数 (#1)






作者您好，我有三个问题希望您可以解答一下

关于是否跳过当前block
在训练代码中我看到不管gate的输出是什么，当前的block的运算都不会跳过，这样如果达到加速推理的目的呢？
2.关于ConDivLoss
您没有提供lda_intra_margin和lda_inter_margin这两个值，并且loss_lda的值为0，如果直接按照您的训练usage进行训练，Consistency and Diversity Regularization loss并没有参与训练
3.关于FLOPSL1Loss
我想这个loss应该是用于Customizable Dynamic Routing的，但是没看懂这个写法，您可以指点一下吗

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
